name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - pipelines/*
      - .github/*
      - docs/*
      - README.md
      - CHANGELOG.md
  tags:
    include:
      - v*.*.*

pr:
  - none

pool:
  vmImage: ubuntu-latest

steps:
- task: AppSettingsBuilder@1
  inputs:
    file: appsettings/env.yaml
    stage: 'dev'
    logdir: appsettings
    forbiddenKeywords: 'test,tests,qa,uat,dev'

- task: CmdLine@2
  inputs:
    script: 'pwd && ls -laR'
