name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - pipelines/*
      - .github/*
      - docs/*
      - README.md
      - CHANGELOG.md
  tags:
    include:
      - v*.*.*

pr:
  - none

variables:
  - group: alx-sftp-function

resources:
  repositories:
    - repository: cicd-templates
      type: github
      endpoint: alexandrebdealencar
      name: alexandrebdealencar/alx-cicd-templates
      ref: refs/heads/deploy-to-functionapp

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage_1
    displayName: Deploy to Azure
    condition: >
        or(
          and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')),
          and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/hotfix/')),
          and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
        )
    jobs:
      - template: "jobs/deploy-to-function.yaml@cicd-templates"
        parameters:
          azureSubscription: $(SUBSCRIPTION)
          serviceConnection: $(SERVICE_CONNECTION)
          deployKeyVaultResourceGroup: $(RG_NAME)
          deployKeyVaultName: $(KEY_VAULT)
          deployArtifactName: appsettings
          envs:
            resourceGroup: alx-$(RG_NAME)
            appName: alx-$(APP_NAME)
